#include "Swarm/KBEnemyDirector.h"

#include "Combat/KBStatSheetComponent.h"
#include "Core/KBPlayerState.h"
#include "Data/KBEnemyArchetype.h"
#include "EngineUtils.h"
#include "KBConsoleVariables.h"
#include "KBGameSettings.h"
#include "KillBugs.h"
#include "GameFramework/PlayerController.h"
#include "KBStats.h"
#include "Net/UnrealNetwork.h"
#include "Swarm/KBGoreComponent.h"
#include "Swarm/KBEnemyVisualizerComponent.h"
#include "Swarm/KBSwarmAudioComponent.h"
#include "UObject/ConstructorHelpers.h"

DEFINE_STAT(STAT_KB_SwarmSim);
DEFINE_STAT(STAT_KB_SwarmNetSync);
DEFINE_STAT(STAT_KB_SwarmCount);

namespace
{

	/**
	 * Placeholder archetypes, loaded by path so the swarm runs with no editor setup.
	 * These assets are generated by Tools/kb_setup_enemies.py. Move this to a
	 * designer-editable UPROPERTY on a Blueprint subclass once one exists.
	 */
	const TCHAR* const PlaceholderArchetypePaths[] =
	{
		TEXT("/Game/KillBugs/Enemies/DA_Bug_Grunt.DA_Bug_Grunt"),
		TEXT("/Game/KillBugs/Enemies/DA_Bug_Runner.DA_Bug_Runner"),
		TEXT("/Game/KillBugs/Enemies/DA_Bug_Brute.DA_Bug_Brute")
	};
}

AKBEnemyDirector::AKBEnemyDirector()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.TickGroup = TG_PrePhysics;

	USceneComponent* SceneRoot = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	SetRootComponent(SceneRoot);

	Visualizer = CreateDefaultSubobject<UKBEnemyVisualizerComponent>(TEXT("SwarmVisualizer"));
	Visualizer->SetupAttachment(SceneRoot);

	// Death splatter and slime. A sibling of the visualizer rather than part of it: the
	// visualizer draws bugs, this owns the decal pool and the effect budget, and the only thing
	// between them is a single call when a bug stops being drawn.
	Gore = CreateDefaultSubobject<UKBGoreComponent>(TEXT("Gore"));
	Gore->SetupAttachment(SceneRoot);

	// Bug movement sound. A third sibling for the same reason the gore component is a sibling
	// of the visualizer: it reads the visualizer's views and owns its own budget, and there is
	// nothing between them but that read. It has its own tick group, which is what lets it run
	// on a client - this actor's own Tick is authority-gated and returns immediately there.
	SwarmAudio = CreateDefaultSubobject<UKBSwarmAudioComponent>(TEXT("SwarmAudio"));
	SwarmAudio->SetupAttachment(SceneRoot);

	// One actor replicates the whole swarm, so it must never be culled for relevancy and
	// never go dormant - dormancy would stop the fast array from being sent at all.
	bReplicates = true;
	bAlwaysRelevant = true;
	// bReplicateMovement is private on AActor; the setter is the only way in (and the default
	// is already false - the director never moves).
	SetReplicateMovement(false);
	SetNetDormancy(DORM_Never);
	SetNetUpdateFrequency(15.f);

	static ConstructorHelpers::FObjectFinder<UKBEnemyArchetype> Grunt(PlaceholderArchetypePaths[0]);
	static ConstructorHelpers::FObjectFinder<UKBEnemyArchetype> Runner(PlaceholderArchetypePaths[1]);
	static ConstructorHelpers::FObjectFinder<UKBEnemyArchetype> Brute(PlaceholderArchetypePaths[2]);

	if (Grunt.Succeeded()) { Archetypes.Add(Grunt.Object); }
	if (Runner.Succeeded()) { Archetypes.Add(Runner.Object); }
	if (Brute.Succeeded()) { Archetypes.Add(Brute.Object); }
}

void AKBEnemyDirector::BeginPlay()
{
	Super::BeginPlay();

	Grid.Reset(GridCellSize, FVector::ZeroVector, KBSettings().ArenaHalfExtent);
}

void AKBEnemyDirector::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(AKBEnemyDirector, ReplicatedEnemies);
}

void AKBEnemyDirector::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	// Clients do nothing here: their swarm arrives through replication, and the visualizer
	// reads the replicated array directly.
	if (!HasAuthority())
	{
		return;
	}

	// A run that has ended stops the swarm where it stands.
	//
	// Freezing rather than culling, and the difference is not cosmetic. Culling removes every
	// survivor from the replicated array at once - and every machine derives "a bug died" from
	// exactly that removal, because a death over the network IS an item vanishing. So ending a run
	// over a field of 186 bugs read as 186 deaths at once: 186 splats and 186 puddles into the
	// frame the summary appeared, and a burst of Niagara work in the twelve seconds before a map
	// load. Frozen, they simply stop: no movement, no biting, nothing to remove.
	//
	// SyncReplication still runs so the array is never left stale; the values just stop changing.
	if (bSimulationFrozen)
	{
		SyncReplication(DeltaSeconds);
		return;
	}

	const double StartSeconds = FPlatformTime::Seconds();
	SimulateSwarm(DeltaSeconds);
	const double AfterSimSeconds = FPlatformTime::Seconds();
	SyncReplication(DeltaSeconds);
	TickContactDamage(DeltaSeconds);

	const float PerfLogInterval = CVarKBSwarmPerfLog.GetValueOnGameThread();
	if (PerfLogInterval > 0.f)
	{
		PerfSimSeconds += AfterSimSeconds - StartSeconds;
		PerfNetSeconds += FPlatformTime::Seconds() - AfterSimSeconds;
		++PerfFrames;
		PerfElapsed += DeltaSeconds;

		if (PerfElapsed >= PerfLogInterval)
		{
			// Player health rides along with the swarm stats on purpose: while tuning contact
			// damage, "is the swarm actually threatening?" is the question you are asking, and
			// a bug count alone cannot answer it.
			//
			// The player's POSITION rides along for the same class of reason: several things move
			// the pawn rather than the player (weapon recoil, and later whatever else shoves
			// them), and a headless run has no other way to say where the pawn ended up. Without
			// this the only position readout is the bullet-spawn diagnostic, which stops after ten
			// shots - far too early to watch a push settle, and it reads the position of whoever
			// fired rather than of the player.
			float HealthPercent = -1.f;
			FVector PlayerLocation = FVector::ZeroVector;
			bool bHasPlayerLocation = false;

			if (const UWorld* PerfWorld = GetWorld())
			{
				for (FConstPlayerControllerIterator It = PerfWorld->GetPlayerControllerIterator(); It; ++It)
				{
					const APlayerController* PlayerController = It->Get();
					const APawn* Pawn = PlayerController ? PlayerController->GetPawn() : nullptr;
					if (!Pawn)
					{
						continue;
					}

					PlayerLocation = Pawn->GetActorLocation();
					bHasPlayerLocation = true;

					if (const UKBStatSheetComponent* Stats = Pawn->FindComponentByClass<UKBStatSheetComponent>())
					{
						HealthPercent = Stats->GetHealthFraction() * 100.f;
						break;
					}
				}
			}

			const double Frames = FMath::Max(PerfFrames, 1);
			UE_LOG(LogKillBugs, Display,
				TEXT("Swarm perf | %d bugs | sim %.3f ms | net %.3f ms | health %.0f%% | ")
				TEXT("player (%s) | %.0f fps"),
				Sim.Num(),
				PerfSimSeconds / Frames * 1000.0,
				PerfNetSeconds / Frames * 1000.0,
				HealthPercent,
				bHasPlayerLocation
					? *FString::Printf(TEXT("%.0f,%.0f,%.0f"),
					                   PlayerLocation.X, PlayerLocation.Y, PlayerLocation.Z)
					: TEXT("none"),
				Frames / PerfElapsed);

			PerfSimSeconds = 0.0;
			PerfNetSeconds = 0.0;
			PerfFrames = 0;
			PerfElapsed = 0.f;
		}
	}
}

void AKBEnemyDirector::SimulateSwarm(float DeltaSeconds)
{
	SCOPE_CYCLE_COUNTER(STAT_KB_SwarmSim);
	SET_DWORD_STAT(STAT_KB_SwarmCount, Sim.Num());

	const UWorld* World = GetWorld();
	if (!World || Sim.Num() == 0)
	{
		return;
	}

	// One pass builds the neighbour grid the separation step reads.
	Grid.Rebuild(Sim);

	const float Now = World->GetTimeSeconds();

	for (int32 Index = 0; Index < Sim.Num(); ++Index)
	{
		FKBEnemySim& Enemy = Sim[Index];

		const UKBEnemyArchetype* Archetype =
			Archetypes.IsValidIndex(Enemy.ArchetypeIndex) ? Archetypes[Enemy.ArchetypeIndex].Get() : nullptr;
		if (!Archetype)
		{
			continue;
		}

		// ---- Target maintenance, staggered ----
		// A deterministic per-bug offset spreads the cost evenly instead of re-targeting all
		// 500 on the same frame.
		if (Now >= Enemy.NextThinkTime)
		{
			const float OffsetFraction = static_cast<float>(Enemy.StableId % 16) / 15.f;
			Enemy.NextThinkTime = Now + 0.4f * (0.75f + 0.5f * OffsetFraction);

			// Re-validated every think. A player who quits mid-wave must not leave this bug
			// chasing a dangling pointer or frozen in place.
			if (!Enemy.Target.IsValid())
			{
				Enemy.Target = SelectTargetFor(Enemy);
			}
		}

		// ---- Steering ----
		const float Speed = Archetype->GetSpeedForWave(CurrentWaveIndex) * EnemySpeedScale;
		FVector DesiredVelocity = FVector::ZeroVector;
		const AActor* Target = Enemy.Target.Get();

		if (!Target)
		{
			// No living player to chase - they are all down, respawning, or have not joined
			// yet. Drift toward the arena centre instead of standing still, so the swarm
			// keeps converging and does not freeze in its spawn ring.
			FVector ToCentre = -Enemy.Location;
			ToCentre.Z = 0.f;
			if (ToCentre.SizeSquared() > FMath::Square(200.f))
			{
				DesiredVelocity = ToCentre.GetSafeNormal() * Speed * 0.5f;
			}
		}
		else
		{
			FVector ToTarget = Target->GetActorLocation() - Enemy.Location;
			ToTarget.Z = 0.f;
			const float Distance = ToTarget.Size();

			if (Distance > KINDA_SMALL_NUMBER)
			{
				const FVector Direction = ToTarget / Distance;

				if (Archetype->Steering == EKBSteeringBehavior::Orbit)
				{
					// ALWAYS close in. The radial component never reverses sign, so the bug can
					// never settle into a stable orbit - it just takes a curving path in.
					//
					// An earlier version scaled the radial term by the distance error and let
					// the tangential term dominate, which meant that at PreferredDistance the
					// radial term hit zero and the bug circled forever without ever arriving.
					const float Preferred = FMath::Max(Archetype->PreferredDistance, 1.f);
					const float CurveAmount = Distance > Preferred ? 0.25f : 0.6f;
					const FVector Tangent(-Direction.Y, Direction.X, 0.f);

					DesiredVelocity = (Direction + Tangent * CurveAmount).GetSafeNormal() * Speed;
				}
				else
				{
					DesiredVelocity = Direction * Speed;
				}
			}
		}

		// ---- Separation ----
		// Capped at 8 neighbours: past that the correction is visually identical but the cost
		// keeps climbing with the square of the local density.
		SeparationScratch.Reset();
		Grid.QuerySphere(Enemy.Location, SeparationRadius, Index, Sim, SeparationScratch);

		FVector Separation = FVector::ZeroVector;
		int32 NeighbourCount = 0;
		const float SeparationRadiusSq = SeparationRadius * SeparationRadius;

		for (const int32 Neighbour : SeparationScratch)
		{
			if (NeighbourCount >= 8)
			{
				break;
			}

			FVector Away = Enemy.Location - Sim[Neighbour].Location;
			Away.Z = 0.f;
			const float DistanceSq = Away.SizeSquared();
			if (DistanceSq > KINDA_SMALL_NUMBER && DistanceSq < SeparationRadiusSq)
			{
				const float Distance = FMath::Sqrt(DistanceSq);
				Separation += (Away / Distance) * (1.f - Distance / SeparationRadius);
				++NeighbourCount;
			}
		}

		if (NeighbourCount > 0)
		{
			DesiredVelocity += Separation.GetSafeNormal() * Speed * SeparationStrength;
		}

		// ---- Integrate ----
		Enemy.Velocity = FMath::VInterpConstantTo(Enemy.Velocity, DesiredVelocity, DeltaSeconds, Archetype->Acceleration);
		Enemy.Location += Enemy.Velocity * DeltaSeconds;

		// Hard backstop: the walls should hold them, but a tunnelling bug must never end up
		// outside the arena where it can never be reached.
		const float Limit = FMath::Max(KBSettings().ArenaHalfExtent - Archetype->BodyRadius, 0.f);
		Enemy.Location.X = FMath::Clamp(Enemy.Location.X, -Limit, Limit);
		Enemy.Location.Y = FMath::Clamp(Enemy.Location.Y, -Limit, Limit);
		Enemy.Location.Z = 0.f;
	}
}

void AKBEnemyDirector::SyncReplication(float DeltaSeconds)
{
	SCOPE_CYCLE_COUNTER(STAT_KB_SwarmNetSync);

	NetSyncAccumulator += DeltaSeconds;
	if (NetSyncAccumulator < NetSyncInterval)
	{
		return;
	}

	// Advance by whole intervals so the stagger pattern stays stable across frame rates.
	NetSyncAccumulator = FMath::Fmod(NetSyncAccumulator, NetSyncInterval);
	++NetSyncFrame;

	// Sim and ReplicatedEnemies are kept index-parallel by AddEnemy / ApplyDamageToEnemy.
	const int32 Count = FMath::Min(Sim.Num(), ReplicatedEnemies.Items.Num());

	for (int32 Index = 0; Index < Count; ++Index)
	{
		const FKBEnemySim& Enemy = Sim[Index];
		FKBEnemyNetItem& Item = ReplicatedEnemies.Items[Index];

		if (NetStaggerStride > 1
			&& ((Enemy.StableId + static_cast<int32>(NetSyncFrame)) % NetStaggerStride) != 0)
		{
			continue;
		}

		const uint8 NewHealthPct = static_cast<uint8>(FMath::RoundToInt(Enemy.GetHealthPct() * 255.f));
		const bool bMovedEnough =
			FVector::DistSquared(Item.LastReplicatedLocation, Enemy.Location) >= FMath::Square(NetPositionThreshold);

		if (!bMovedEnough && NewHealthPct == Item.HealthPct)
		{
			continue;
		}

		float YawDegrees = FKBEnemyNetItem::UnpackYaw(Item.Yaw);
		if (!Enemy.Velocity.IsNearlyZero())
		{
			YawDegrees = Enemy.Velocity.Rotation().Yaw;
		}

		Item.Location = Enemy.Location;
		Item.Yaw = FKBEnemyNetItem::PackYaw(YawDegrees);
		Item.HealthPct = NewHealthPct;
		Item.LastReplicatedLocation = Enemy.Location;

		ReplicatedEnemies.MarkItemDirty(Item);
	}
}

AActor* AKBEnemyDirector::SelectTargetFor(const FKBEnemySim& Enemy) const
{
	const UWorld* World = GetWorld();
	if (!World)
	{
		return nullptr;
	}

	// Only players are candidates, and there are at most four, so this is a linear scan.
	// (SeekLowestHealth will diverge from SeekNearestPlayer once player health exists in
	// Phase 3; until then every behaviour targets the nearest living player.)
	AActor* BestTarget = nullptr;
	float BestDistanceSq = TNumericLimits<float>::Max();

	for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
	{
		const APlayerController* PlayerController = It->Get();
		APawn* Pawn = PlayerController ? PlayerController->GetPawn() : nullptr;
		if (!IsValid(Pawn))
		{
			continue;
		}

		const float DistanceSq = FVector::DistSquared2D(Pawn->GetActorLocation(), Enemy.Location);
		if (DistanceSq < BestDistanceSq)
		{
			BestDistanceSq = DistanceSq;
			BestTarget = Pawn;
		}
	}

	return BestTarget;
}

int32 AKBEnemyDirector::AddEnemy(const FVector& Location, int32 ArchetypeIndex)
{
	if (!HasAuthority() || Sim.Num() >= KBSettings().MaxEnemies || !Archetypes.IsValidIndex(ArchetypeIndex))
	{
		return INDEX_NONE;
	}

	const UKBEnemyArchetype* Archetype = Archetypes[ArchetypeIndex].Get();
	if (!Archetype)
	{
		return INDEX_NONE;
	}

	const int32 StableId = NextStableId++;

	FKBEnemySim& Enemy = Sim.AddDefaulted_GetRef();
	Enemy.Location = Location;
	Enemy.Velocity = FVector::ZeroVector;
	Enemy.MaxHealth = Archetype->GetHealthForWave(CurrentWaveIndex);
	Enemy.Health = Enemy.MaxHealth;
	Enemy.ArchetypeIndex = static_cast<uint8>(ArchetypeIndex);
	Enemy.StableId = StableId;
	Enemy.NextThinkTime = 0.f; // think on the next tick

	FKBEnemyNetItem& Item = ReplicatedEnemies.Items.AddDefaulted_GetRef();
	Item.StableId = StableId;
	Item.Location = Location;
	Item.ArchetypeIndex = static_cast<uint8>(ArchetypeIndex);
	Item.HealthPct = 255;
	Item.LastReplicatedLocation = Location;
	ReplicatedEnemies.MarkItemDirty(Item);

	return Sim.Num() - 1;
}

void AKBEnemyDirector::SpawnSwarm(int32 Count, const FVector& Centre, float SpawnRadius)
{
	if (!HasAuthority())
	{
		return;
	}

	// Clear the sim and the replicated array together: SyncReplication relies on the two
	// being index-parallel.
	Sim.Reset();
	ReplicatedEnemies.Items.Reset();
	ReplicatedEnemies.MarkArrayDirty();

	Count = FMath::Clamp(Count, 0, KBSettings().MaxEnemies);
	if (Count == 0 || Archetypes.Num() == 0)
	{
		return;
	}

	// Sqrt on a uniformly random squared radius gives an even spread over the annulus rather
	// than a crowd bunched at the centre.
	const float InnerRadius = SpawnRadius * 0.6f;
	const float InnerRadiusSq = InnerRadius * InnerRadius;
	const float OuterRadiusSq = SpawnRadius * SpawnRadius;

	for (int32 Index = 0; Index < Count; ++Index)
	{
		const float Angle = FMath::FRandRange(0.f, 2.f * PI);
		const float Radius = FMath::Sqrt(FMath::FRandRange(InnerRadiusSq, OuterRadiusSq));
		const FVector Location = Centre + FVector(FMath::Cos(Angle) * Radius, FMath::Sin(Angle) * Radius, 0.f);

		AddEnemy(Location, FMath::RandHelper(Archetypes.Num()));
	}
}

void AKBEnemyDirector::SpawnBatch(int32 Count, const FVector& Centre, float SpawnRadius)
{
	if (!HasAuthority() || Count <= 0 || Archetypes.Num() == 0)
	{
		return;
	}

	const int32 Allowed = FMath::Min(Count, KBSettings().MaxEnemies - Sim.Num());
	const float InnerRadius = SpawnRadius * 0.6f;
	const float InnerRadiusSq = InnerRadius * InnerRadius;
	const float OuterRadiusSq = SpawnRadius * SpawnRadius;

	for (int32 Index = 0; Index < Allowed; ++Index)
	{
		const float Angle = FMath::FRandRange(0.f, 2.f * PI);
		const float Radius = FMath::Sqrt(FMath::FRandRange(InnerRadiusSq, OuterRadiusSq));
		const FVector Location = Centre + FVector(FMath::Cos(Angle) * Radius, FMath::Sin(Angle) * Radius, 0.f);

		AddEnemy(Location, FMath::RandHelper(Archetypes.Num()));
	}
}

void AKBEnemyDirector::SetEnemyScaling(float InDamageTakenScale, float InSpeedScale)
{
	if (!HasAuthority())
	{
		return;
	}

	EnemyDamageTakenScale = FMath::Max(0.f, InDamageTakenScale);
	EnemySpeedScale = FMath::Max(0.f, InSpeedScale);
}

FVector AKBEnemyDirector::GetSwarmFocusLocation() const
{
	const UWorld* World = GetWorld();
	if (!World)
	{
		return FVector::ZeroVector;
	}

	FVector Sum = FVector::ZeroVector;
	int32 Count = 0;

	for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
	{
		const APlayerController* PlayerController = It->Get();
		const APawn* Pawn = PlayerController ? PlayerController->GetPawn() : nullptr;
		if (!IsValid(Pawn))
		{
			continue;
		}

		Sum += Pawn->GetActorLocation();
		++Count;
	}

	return Count > 0 ? Sum / static_cast<float>(Count) : FVector::ZeroVector;
}

void AKBEnemyDirector::SpawnBatchOffscreen(int32 Count, float MinDistance, float MaxDistance)
{
	if (!HasAuthority() || Count <= 0 || Archetypes.Num() == 0)
	{
		return;
	}

	const FVector Focus = GetSwarmFocusLocation();
	const float Arena = FMath::Max(KBSettings().ArenaHalfExtent - 300.f, 500.f);
	const float OuterDistance = FMath::Max(MaxDistance, MinDistance + 1.f);

	for (int32 Index = 0; Index < Count && Sim.Num() < KBSettings().MaxEnemies; ++Index)
	{
		FVector SpawnLocation = FVector::ZeroVector;
		bool bPlaced = false;

		// Try a few directions and take the first that lands both inside the arena and far
		// enough away. When the player is cornered there is genuinely nowhere off-screen, so
		// this gives up and takes the best clamped effort rather than spawning nothing.
		for (int32 Attempt = 0; Attempt < 12 && !bPlaced; ++Attempt)
		{
			const float Angle = FMath::FRandRange(0.f, 2.f * PI);
			const float Distance = FMath::FRandRange(MinDistance, OuterDistance);

			FVector Candidate = Focus + FVector(FMath::Cos(Angle) * Distance, FMath::Sin(Angle) * Distance, 0.f);

			// Pull it back inside the arena if it overshot, keeping the direction.
			Candidate.X = FMath::Clamp(Candidate.X, -Arena, Arena);
			Candidate.Y = FMath::Clamp(Candidate.Y, -Arena, Arena);
			Candidate.Z = 0.f;

			if (FVector::DistSquared2D(Candidate, Focus) >= FMath::Square(MinDistance))
			{
				SpawnLocation = Candidate;
				bPlaced = true;
			}
		}

		if (!bPlaced)
		{
			// Cornered: spawn on the arena edge in the direction that is furthest from the
			// player. Still on screen, but it is the best that geometry allows.
			FVector Away = (Focus - FVector::ZeroVector);
			Away.Z = 0.f;
			Away = Away.IsNearlyZero() ? FVector(1.f, 0.f, 0.f) : Away.GetSafeNormal();
			SpawnLocation = -Away * Arena;

			// Say so once. A silent fallback would look exactly like the off-screen spawning
			// working, while actually being the thing it was meant to prevent.
			static bool bWarnedAboutFallback = false;
			if (!bWarnedAboutFallback)
			{
				bWarnedAboutFallback = true;
				UE_LOG(LogKillBugs, Warning,
					TEXT("Could not place a spawn %.0f units from the player inside the arena; ")
					TEXT("used the arena edge instead. The player is probably cornered, or ")
					TEXT("MinSpawnDistance is too large for the arena."),
					MinDistance);
			}
		}

		AddEnemy(SpawnLocation, FMath::RandHelper(Archetypes.Num()));
	}
}

void AKBEnemyDirector::CullAllRemaining()
{
	if (!HasAuthority())
	{
		return;
	}

	Sim.Reset();
	ReplicatedEnemies.Items.Reset();
	ReplicatedEnemies.MarkArrayDirty();
}

bool AKBEnemyDirector::ApplyDamageToEnemy(int32 SimIndex, float Damage, AKBPlayerState* Killer)
{
	if (!HasAuthority() || Damage <= 0.f || !Sim.IsValidIndex(SimIndex))
	{
		return false;
	}

	FKBEnemySim& Enemy = Sim[SimIndex];

	// Phase scaling: the same shot hurts far more during Explore than during a wave.
	Enemy.Health -= Damage * EnemyDamageTakenScale;

	const UWorld* World = GetWorld();
	Enemy.HitFlashEndTime = (World ? World->GetTimeSeconds() : 0.f) + 0.08f;

	if (Enemy.Health > 0.f)
	{
		return false;
	}

	// Reward before the entry disappears: the archetype is the only thing that knows the
	// value, and it is gone once the sim entry is removed.
	if (IsValid(Killer))
	{
		if (const UKBEnemyArchetype* Archetype =
			Archetypes.IsValidIndex(Enemy.ArchetypeIndex) ? Archetypes[Enemy.ArchetypeIndex].Get() : nullptr)
		{
			// The killer's own XP multiplier, not the archetype's raw value.
			//
			// This multiplier was already folded into the stat sheet and exposed as
			// GetXpMultiplier(), but nothing ever called it - so the card that grants +15% XP
			// was a card that did nothing at all. Read at the moment of the kill rather than
			// cached, for the same reason weapons read the damage multiplier at fire time: a
			// card picked mid-run should change the very next kill.
			float XpMultiplier = 1.f;
			if (const APawn* KillerPawn = Killer->GetPawn())
			{
				if (const UKBStatSheetComponent* KillerStats =
					KillerPawn->FindComponentByClass<UKBStatSheetComponent>())
				{
					XpMultiplier = KillerStats->GetXpMultiplier();
				}
			}

			Killer->AddXP(FMath::RoundToInt(Archetype->XpValue * XpMultiplier));
			Killer->AddGold(Archetype->GoldValue);
		}
	}

	// Death is a removal from both arrays. Removing at the same index preserves the
	// index-parallel invariant, and on clients the visualizer drops the instance when the
	// entry stops appearing.
	Sim.RemoveAt(SimIndex);
	if (ReplicatedEnemies.Items.IsValidIndex(SimIndex))
	{
		ReplicatedEnemies.Items.RemoveAt(SimIndex);
	}
	ReplicatedEnemies.MarkArrayDirty();

	return true;
}

void AKBEnemyDirector::TickContactDamage(float DeltaSeconds)
{
	// Its own cadence rather than per frame: biting is a rate, and applying it every frame
	// would make damage scale with frame rate.
	ContactDamageAccumulator += DeltaSeconds;
	if (ContactDamageAccumulator < KBSettings().ContactDamageInterval)
	{
		return;
	}
	ContactDamageAccumulator = 0.f;

	const UWorld* World = GetWorld();
	if (!World || Sim.Num() == 0)
	{
		return;
	}

	// The widest reach any archetype can have, for the broad phase below. Computed once per
	// cadence rather than per player, and per archetype rather than per bug.
	float MaxBodyRadius = 0.f;
	for (const TObjectPtr<UKBEnemyArchetype>& Archetype : Archetypes)
	{
		if (Archetype)
		{
			MaxBodyRadius = FMath::Max(MaxBodyRadius, Archetype->BodyRadius);
		}
	}

	for (FConstPlayerControllerIterator It = World->GetPlayerControllerIterator(); It; ++It)
	{
		APlayerController* PlayerController = It->Get();
		APawn* Pawn = PlayerController ? PlayerController->GetPawn() : nullptr;
		if (!IsValid(Pawn))
		{
			continue;
		}

		if (const AKBPlayerState* PlayerState = PlayerController->GetPlayerState<AKBPlayerState>())
		{
			if (PlayerState->IsDowned())
			{
				continue; // already out; do not keep chewing a corpse
			}
		}

		UKBStatSheetComponent* Stats = Pawn->FindComponentByClass<UKBStatSheetComponent>();
		if (!Stats)
		{
			continue;
		}

		// Contact is measured EDGE TO EDGE, and the bug's edge is its BodyRadius - the same number
		// that already drives separation, weapon hit tests and the blob shadow, and the number the
		// mesh is scaled to match.
		//
		// A single centre-to-centre radius cannot be right for both ends of the size range. At the
		// old fixed 110 from the player's centre, a Runner (BodyRadius 28) started biting with
		// ~48 units of visible empty space between the two bodies, while a Brute (85) had to be
		// overlapping the player before it counted - so small bugs bit from thin air and the big
		// one never seemed to reach. Both are the same bug: the test ignored the model.
		const float PlayerRadius = Pawn->GetSimpleCollisionRadius();

		// Broad phase at the widest reach, so the grid never culls a bug the exact test would keep.
		//
		// Reset first: this array is a member scratch buffer, and QuerySphere only APPENDS. Without
		// the reset it accumulates across players and across frames, and once any bug dies the
		// older, longer indices point past the end of Sim and the bounds check fires.
		ContactScratch.Reset();
		Grid.QuerySphere(Pawn->GetActorLocation(), PlayerRadius + MaxBodyRadius + KBSettings().ContactGap,
			INDEX_NONE, Sim, ContactScratch);
		if (ContactScratch.Num() == 0)
		{
			continue;
		}

		float Damage = 0.f;
		int32 Biters = 0;
		for (const int32 Index : ContactScratch)
		{
			if (Biters >= KBSettings().MaxSimultaneousContacts)
			{
				break;
			}

			const UKBEnemyArchetype* Archetype =
				Archetypes.IsValidIndex(Sim[Index].ArchetypeIndex) ? Archetypes[Sim[Index].ArchetypeIndex].Get() : nullptr;
			if (!Archetype)
			{
				continue;
			}

			// Narrow phase: this bug's own reach, not the widest one.
			const float Reach = PlayerRadius + Archetype->BodyRadius + KBSettings().ContactGap;
			if (FVector::DistSquared2D(Pawn->GetActorLocation(), Sim[Index].Location) > Reach * Reach)
			{
				continue;
			}

			Damage += Archetype->GetContactDamageForWave(CurrentWaveIndex);
			++Biters;
		}

		if (Biters > 0)
		{
			Stats->ApplyDamage(Damage);
		}
	}
}

// ---------------------------------------------------------------------------------------
// Queries used by weapons
// ---------------------------------------------------------------------------------------

int32 AKBEnemyDirector::FindNearestEnemy(const FVector& Origin, float MaxRange, FVector& OutLocation) const
{
	int32 BestIndex = INDEX_NONE;
	float BestDistanceSq = FMath::Square(MaxRange);

	for (int32 Index = 0; Index < Sim.Num(); ++Index)
	{
		const float DistanceSq = FVector::DistSquared2D(Sim[Index].Location, Origin);
		if (DistanceSq < BestDistanceSq)
		{
			BestDistanceSq = DistanceSq;
			BestIndex = Index;
		}
	}

	if (BestIndex != INDEX_NONE)
	{
		OutLocation = Sim[BestIndex].Location;
	}
	return BestIndex;
}

int32 AKBEnemyDirector::ApplyRadialDamage(const FVector& Centre, float Radius, float Damage, AKBPlayerState* Killer)
{
	if (!HasAuthority())
	{
		return 0;
	}

	// Collect first, then damage in descending index order: ApplyDamageToEnemy removes dead
	// entries, and removing a lower index would shift every index above it.
	TArray<int32> Hits;
	for (int32 Index = 0; Index < Sim.Num(); ++Index)
	{
		// Same rule as the line test: a burst catches a bug whose BODY is in range, not merely
		// one whose centre is. See ApplyDamageAlongSegment.
		const UKBEnemyArchetype* Archetype =
			Archetypes.IsValidIndex(Sim[Index].ArchetypeIndex) ? Archetypes[Sim[Index].ArchetypeIndex].Get() : nullptr;
		const float BodyRadius = Archetype ? Archetype->BodyRadius : 0.f;
		const float EffectiveRadius = Radius + BodyRadius;

		if (FVector::DistSquared2D(Sim[Index].Location, Centre) <= FMath::Square(EffectiveRadius))
		{
			Hits.Add(Index);
		}
	}

	int32 Kills = 0;
	for (int32 Hit = Hits.Num() - 1; Hit >= 0; --Hit)
	{
		Kills += ApplyDamageToEnemy(Hits[Hit], Damage, Killer) ? 1 : 0;
	}
	return Kills;
}

bool AKBEnemyDirector::ApplyDamageAlongSegment(const FVector& Start, const FVector& End, float Radius,
                                               float Damage, AKBPlayerState* Killer, FVector* OutHitLocation)
{
	if (!HasAuthority())
	{
		return false;
	}

	const FVector Segment = End - Start;
	const float SegmentLengthSq = Segment.SizeSquared();
	if (SegmentLengthSq <= KINDA_SMALL_NUMBER)
	{
		return false;
	}

	// Closest bug to the line, within Radius, and in front of the muzzle.
	int32 BestIndex = INDEX_NONE;
	float BestAlong = TNumericLimits<float>::Max();

	for (int32 Index = 0; Index < Sim.Num(); ++Index)
	{
		const FVector ToEnemy = Sim[Index].Location - Start;
		const float Along = FVector::DotProduct(ToEnemy, Segment) / SegmentLengthSq;
		if (Along < 0.f || Along > 1.f)
		{
			continue;
		}

		// The shot's radius PLUS the target's body radius.
		//
		// Testing against the enemy's centre alone means a small projectile has to pass within
		// its own width of that centre - while the bug's visible body is 28 to 85 units
		// across. Pellets that visibly strike the body sail through doing nothing, which reads
		// as "I hit it and it did not die". Enemies are not points; they are the size they are
		// drawn.
		const UKBEnemyArchetype* Archetype =
			Archetypes.IsValidIndex(Sim[Index].ArchetypeIndex) ? Archetypes[Sim[Index].ArchetypeIndex].Get() : nullptr;
		const float BodyRadius = Archetype ? Archetype->BodyRadius : 0.f;
		const float EffectiveRadius = Radius + BodyRadius;

		const FVector ClosestPoint = Start + Segment * Along;
		if (FVector::DistSquared2D(ClosestPoint, Sim[Index].Location) > EffectiveRadius * EffectiveRadius)
		{
			continue;
		}

		// Hit the nearest bug along the ray, not merely the nearest to it.
		if (Along < BestAlong)
		{
			BestAlong = Along;
			BestIndex = Index;
		}
	}

	if (BestIndex == INDEX_NONE)
	{
		return false;
	}

	if (OutHitLocation)
	{
		// The bug's own position, not the closest point on the ray: an impact effect should
		// sit on the body it struck, not float in the air beside it.
		*OutHitLocation = Sim[BestIndex].Location;
	}

	ApplyDamageToEnemy(BestIndex, Damage, Killer);
	return true;
}

// ---------------------------------------------------------------------------------------
// Console commands - the Phase 2 test hooks.
// ---------------------------------------------------------------------------------------

void AKBEnemyDirector::ConsoleSetSwarmCount(const TArray<FString>& Args, UWorld* World)
{
	if (!World)
	{
		return;
	}

	const int32 Count = Args.Num() > 0 ? FCString::Atoi(*Args[0]) : 500;

	for (TActorIterator<AKBEnemyDirector> It(World); It; ++It)
	{
		It->SpawnSwarm(Count, FVector::ZeroVector, 3000.f);
		UE_LOG(LogKillBugs, Display, TEXT("Swarm set to %d"), It->GetEnemyCount());
		return;
	}

	UE_LOG(LogKillBugs, Warning, TEXT("No AKBEnemyDirector in this world"));
}

void AKBEnemyDirector::ConsoleKillEnemies(const TArray<FString>& Args, UWorld* World)
{
	if (!World)
	{
		return;
	}

	const int32 Count = Args.Num() > 0 ? FCString::Atoi(*Args[0]) : 50;

	for (TActorIterator<AKBEnemyDirector> It(World); It; ++It)
	{
		const int32 Before = It->GetEnemyCount();
		for (int32 Index = 0; Index < Count && It->GetEnemyCount() > 0; ++Index)
		{
			It->ApplyDamageToEnemy(FMath::RandHelper(It->GetEnemyCount()), 1.0e9f, nullptr);
		}
		UE_LOG(LogKillBugs, Display, TEXT("Killed %d of %d"), Before - It->GetEnemyCount(), Before);
		return;
	}

	UE_LOG(LogKillBugs, Warning, TEXT("No AKBEnemyDirector in this world"));
}

static FAutoConsoleCommandWithWorldAndArgs KBConsoleSwarmCount(
	TEXT("KB.Swarm.Count"),
	TEXT("KB.Swarm.Count <n> - replace the swarm with n placeholder bugs (default 500)."),
	FConsoleCommandWithWorldAndArgsDelegate::CreateStatic(&AKBEnemyDirector::ConsoleSetSwarmCount));

static FAutoConsoleCommandWithWorldAndArgs KBConsoleSwarmKill(
	TEXT("KB.Swarm.Kill"),
	TEXT("KB.Swarm.Kill <n> - kill n random bugs, exercising removal replication."),
	FConsoleCommandWithWorldAndArgsDelegate::CreateStatic(&AKBEnemyDirector::ConsoleKillEnemies));
