"""
Generates the placeholder bug archetypes.

Run headlessly:
  UnrealEditor-Cmd.exe <project>.uproject -ExecutePythonScript="<this file>" \
      -unattended -nosplash -nullrhi

The three archetypes are deliberately different in size, speed and health so the swarm reads
as a swarm rather than as one repeated blob, and so the steering behaviours are visibly
distinct while there is no art. AKBEnemyDirector loads them by path in its constructor.

Phase 6 replaces the meshes and materials with real bug art; the tuning here is throwaway.
"""

import unreal

PACKAGE_PATH = "/Game/KillBugs/Enemies"
PREFIX = "[KBEnemies] "


def log(message):
    unreal.log(PREFIX + str(message))


def warn(message):
    unreal.log_warning(PREFIX + str(message))


def load_asset(path):
    asset = unreal.EditorAssetLibrary.load_asset(path)
    if asset is None:
        warn("could not load {}".format(path))
    return asset


def make_archetype(asset_name, mesh_path, material_path, **properties):
    """
    Creates the archetype. It must NOT already exist.

    Regenerating means removing the old assets from OUTSIDE the editor first:

        rm Content/KillBugs/Enemies/DA_Bug_*.uasset

    Both alternatives were tried and both fail:
      * update-in-place - setting a property from Python does not mark the package dirty, so
        the save writes nothing and the edit is lost when the editor closes. It looks like it
        worked, because re-loading in the same process returns the still-modified in-memory
        object. That is how a material change stayed invisible on disk for several rounds.
      * delete-then-create in-editor - delete_asset drops the registry entry but leaves the
        package resident, so the following create_asset fails even after polling and a GC.
    """
    full_path = "{}/{}".format(PACKAGE_PATH, asset_name)

    if unreal.EditorAssetLibrary.does_asset_exist(full_path):
        raise RuntimeError(
            "{} already exists. Remove it from outside the editor first: "
            "rm Content/KillBugs/Enemies/*.uasset".format(full_path))

    factory = unreal.DataAssetFactory()
    factory.set_editor_property("data_asset_class", unreal.KBEnemyArchetype)

    asset = asset_tools.create_asset(asset_name, PACKAGE_PATH, unreal.KBEnemyArchetype, factory)
    if asset is None:
        raise RuntimeError("create_asset failed for {}".format(full_path))

    mesh = load_asset(mesh_path)
    material = load_asset(material_path)

    if mesh is not None:
        asset.set_editor_property("mesh", mesh)
    if material is not None:
        asset.set_editor_property("material", material)

    for key, value in properties.items():
        if value is None:
            # An enum that could not be resolved; leave the property at its C++ default
            # rather than failing the whole asset over a cosmetic difference.
            continue
        try:
            asset.set_editor_property(key, value)
        except Exception as error:  # noqa: BLE001 - report and keep going
            warn("could not set {} on {}: {}".format(key, asset_name, error))

    # save_asset with only_if_is_dirty=False, NOT save_loaded_asset.
    #
    # Setting a property from Python does not reliably mark an existing package dirty, so
    # save_loaded_asset silently writes nothing and every edit is lost when the editor
    # closes. That failure is invisible in-process: re-loading immediately returns the
    # in-memory object, which still looks correct.
    unreal.EditorAssetLibrary.save_asset(full_path, only_if_is_dirty=False)
    log("wrote {}".format(full_path))
    return asset


asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

CUBE = "/Game/LevelPrototyping/Meshes/SM_Cube"
CHAMFER = "/Game/LevelPrototyping/Meshes/SM_ChamferCube"
CYLINDER = "/Game/LevelPrototyping/Meshes/SM_Cylinder"

# Our own material, NOT any of the LevelPrototyping ones.
#
# Every prototype material has bUsedWithInstancedStaticMeshes = False, which means an
# InstancedStaticMeshComponent cannot render it and the renderer silently falls back to the
# engine default material - so all archetypes draw in the same grey regardless of the Base
# Color we set on their dynamic material instances. M_KBEnemy is generated by
# Tools/kb_setup_enemy_material.py with that flag enabled.
ENEMY_MAT = "/Game/KillBugs/Enemies/M_KBEnemy"
TINT_PARAM = "Base Color"

# --- Resolve the reflected types defensively -------------------------------------------
# The exact Python names for game-module enums are not guaranteed, and a missing attribute
# here is a hard crash at import time. Resolve them, report what was found, and carry on
# with defaults for anything missing.
log("KBEnemyArchetype exposed: {}".format(hasattr(unreal, "KBEnemyArchetype")))
log("KB-named attributes: {}".format(sorted(
    name for name in dir(unreal) if "KB" in name or "Steering" in name or "RenderTier" in name)))


def enum_member(*candidate_enum_names, members):
    """Best-effort lookup across the naming conventions UE Python may use."""
    for enum_name in candidate_enum_names:
        enum_type = getattr(unreal, enum_name, None)
        if enum_type is None:
            continue
        for member in members:
            if hasattr(enum_type, member):
                return getattr(enum_type, member)
        warn("none of {} on {}; available: {}".format(
            members, enum_name, [n for n in dir(enum_type) if not n.startswith("_")]))
        return None

    warn("no enum exposed for {}; leaving that property at its default".format(candidate_enum_names))
    return None


# UE Python strips the type prefix from reflected enums: EKBSteeringBehavior becomes
# KBSteeringBehavior. The E-prefixed spellings are kept as fallbacks in case that changes.
STEER_SEEK = enum_member("KBSteeringBehavior", "EKBSteeringBehavior", members=("SEEK_NEAREST_PLAYER",))
STEER_CHARGE = enum_member("KBSteeringBehavior", "EKBSteeringBehavior", members=("CHARGE",))
STEER_ORBIT = enum_member("KBSteeringBehavior", "EKBSteeringBehavior", members=("ORBIT",))
TIER_INSTANCED = enum_member("KBRenderTier", "EKBRenderTier", members=("INSTANCED",))

# --- Grunt: the baseline. Slow, cheap, arrives in numbers. -----------------------------
make_archetype(
    "DA_Bug_Grunt", CUBE, ENEMY_MAT,
    display_name=unreal.Text("Grunt"),
    mesh_scale=unreal.Vector(0.8, 0.8, 0.45),
    tint=unreal.LinearColor(0.42, 0.50, 0.62, 1.0),
    tint_parameter_name=unreal.Name(TINT_PARAM),
    base_health=10.0, health_per_wave=4.0,
    move_speed=270.0, speed_per_wave=8.0,
    contact_damage=5.0, damage_per_wave=1.0,
    body_radius=42.0,
    steering=STEER_SEEK,
    acceleration=900.0, turn_rate_degrees=420.0,
    xp_value=1, gold_value=0,
    render_tier=TIER_INSTANCED,
)

# --- Runner: fast and fragile, flattens the front line. ---------------------------------
make_archetype(
    "DA_Bug_Runner", CHAMFER, ENEMY_MAT,
    display_name=unreal.Text("Runner"),
    mesh_scale=unreal.Vector(0.5, 0.5, 0.3),
    tint=unreal.LinearColor(0.95, 0.48, 0.10, 1.0),
    tint_parameter_name=unreal.Name(TINT_PARAM),
    base_health=6.0, health_per_wave=2.0,
    move_speed=430.0, speed_per_wave=12.0,
    contact_damage=4.0, damage_per_wave=1.0,
    body_radius=28.0,
    steering=STEER_CHARGE,
    acceleration=1600.0, turn_rate_degrees=200.0,
    xp_value=1, gold_value=0,
    render_tier=TIER_INSTANCED,
)

# --- Brute: slow, tanky, orbits so it is not simply a bigger grunt. ---------------------
make_archetype(
    "DA_Bug_Brute", CYLINDER, ENEMY_MAT,
    display_name=unreal.Text("Brute"),
    mesh_scale=unreal.Vector(1.4, 1.4, 0.9),
    tint=unreal.LinearColor(0.62, 0.13, 0.13, 1.0),
    tint_parameter_name=unreal.Name(TINT_PARAM),
    # Tanky, but not a slog: 40 HP is roughly two shotgun blasts, so it reads as heavy
    # without stalling the wave.
    base_health=40.0, health_per_wave=10.0,
    move_speed=170.0, speed_per_wave=5.0,
    contact_damage=12.0, damage_per_wave=2.0,
    body_radius=85.0,
    steering=STEER_ORBIT,
    preferred_distance=320.0,
    acceleration=500.0, turn_rate_degrees=180.0,
    xp_value=5, gold_value=2,
    render_tier=TIER_INSTANCED,
)

# --- Summary, so a run is verifiable from the log alone. --------------------------------
log("--- archetypes ---")
for name in ("DA_Bug_Grunt", "DA_Bug_Runner", "DA_Bug_Brute"):
    path = "{}/{}".format(PACKAGE_PATH, name)
    loaded = unreal.EditorAssetLibrary.load_asset(path)
    if loaded is None:
        warn("MISSING {}".format(path))
        continue
    tint = loaded.get_editor_property("tint")
    material = loaded.get_editor_property("material")
    mesh = loaded.get_editor_property("mesh")
    log("  {:<14} hp={:<6} speed={:<6} radius={:<6} tint=({:.2f},{:.2f},{:.2f})\n"
        "      mesh={} material={}".format(
            name,
            loaded.get_editor_property("base_health"),
            loaded.get_editor_property("move_speed"),
            loaded.get_editor_property("body_radius"),
            tint.r, tint.g, tint.b,
            mesh.get_path_name() if mesh else "NONE",
            material.get_path_name() if material else "NONE"))

log("DONE")

try:
    unreal.SystemLibrary.quit_editor()
except Exception as error:  # noqa: BLE001 - shutdown is best-effort
    warn("quit_editor failed: {}".format(error))
